### ISSUE TITLE
Incorrect folder paths and file references preventing script execution

### ISSUE THREAD

**Issue by kangmincho1** [Harryx2019/CI-STHPAN#4]
Hello, I've encountered several issues while trying to run your code

Folder Path Errors:
   - The "PatchTST_self_supervised" folder does not exist.
   - I modified it to "CI-STHPAN_self_supervised", but it seems the internal paths are also incorrectly set.

Questions:
1. Should I manually correct these path settings myself?
2. If I successfully run the finetune scripts, will I be able to obtain the final results as presented in the paper?

I would appreciate any solutions or additional guidance regarding these issues.

**Comment by Harryx2019** [comment]
Thank you for your interest in our research work, indeed there is an error in the run script in the readme, as an example of running a self-supervised script, the steps are as follows:
Step 1: `cd CI-STHPAN_self_supervised`
Step 2: `bash ./scripts/pretrain/pre_graph_wiki.sh`

It is possible to ensure that code run according to the script will yield experimental results that are consistent with the paper, since all random number seeds have been fixed.

**Comment by kangmincho1** [comment]
Thank you for your kind reply. Your research content was very impressive.

2024년 7월 5일 (금) 오전 11:20, Hongjie Xia ***@***.***>님이 작성:
